service: mock-oauth2-server

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 512
  timeout: 30
  environment:
    NODE_ENV: ${self:provider.stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "arn:aws:logs:*:*:*"

functions:
  api:
    handler: lambda.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
      - http:
          path: /
          method: ANY
          cors: true

package:
  patterns:
    - '!node_modules/.cache/**'
    - '!test/**'
    - '!.nyc_output/**'
    - '!coverage/**'
    - '!.git/**'
    - '!.vscode/**'
    - '!*.md'
    - '!Dockerfile'
    - '!docker-compose.yml'
    - '!.dockerignore'
    - '!memory-bank/**'
    - '!mock-oauth2-server/**'

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 9000
    noPrependStageInUrl: true
